logging:
  level: INFO
  
  loggers:
    com.github.bbijelic.paypal.ipn: TRACE
  
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{35} - %msg%n"
