database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: ${MYSQL_USERNAME}

  # the password
  password: ${MYSQL_PASSWORD}

  # the JDBC URL
  url: jdbc:mysql://${MYSQL_HOST:-default localhost}:${MYSQL_PORT:-default 3306}/${MYSQL_DBNAME}

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.generate_statistics: false
    show_sql: true
    format_sql: true
    use_sql_comments: true

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

logging:
  level: INFO
  
  loggers:
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.github.bbijelic.paypal.ipn: TRACE
  
  appenders:
    - type: file
      currentLogFilename: /app/logs/paypal-ipn.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /app/logs/paypal-ipn-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{txid}] %logger{35} - %msg%n"
      
# Manager configuration
manager:

  # Verification manager
  verification:
    interval: 10
    initialDelay: 0
    verificationUrl: https://www.sandbox.paypal.com/cgi-bin/webscr
    paypalClient:
      timeout: 5000ms
      connectionTimeout: 1000ms
      timeToLive: 1 hour
      cookiesEnabled: false
      maxConnections: 1024
      maxConnectionsPerRoute: 1024
      keepAlive: 0s
    